
const ActionTypes = {
    CHANGE_AMOUNT: 'CHANGE_AMOUNT_PROV',
    INCREMENT_1: 'INCREMENT_1_PROV',
    INCREMENT_5: 'INCREMENT_5_PROV',
    DECREMENT_1: 'DECREMENT_1_PROV',
    DECREMENT_5: 'DECREMENT_5_PROV',
    UPDATE_ACTIVITY: 'UPDATE_ACTIVITY_PROV',
    SOME_ACTION: 'SOME_ACTION_PROV'
}

export default ActionTypes;